package org.mechaRp.mecharp.entity.client;

import net.minecraft.client.render.entity.animation.AnimationDefinition;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class WardrobeAnimation {

    public static final AnimationDefinition WARDROBE_OPEN = AnimationDefinition.Builder.create(1.25f)
            .addBoneAnimation("door",
                    new Transformation(Transformation.Targets.MOVE_ORIGIN,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createTranslationalVector(-0.8f, 0f, -1.4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(-1.49f, 0f, -2.8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createTranslationalVector(-2.05f, 0f, -4.2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(-2.47f, 0f, -5.6f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(-2.72f, 0f, -7f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(-2.78f, 0f, -8.4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(-2.59f, 0f, -9.8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createTranslationalVector(-2.06f, 0f, -11.2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createTranslationalVector(-1.03f, 0f, -12.6f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(1f, 0f, -14f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("door",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, -90f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("loops",
                    new Transformation(Transformation.Targets.MOVE_ORIGIN,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createTranslationalVector(-0.8f, 0f, -1.4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(-1.49f, 0f, -2.8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createTranslationalVector(-2.05f, 0f, -4.2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(-2.47f, 0f, -5.6f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(-2.72f, 0f, -7f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(-2.78f, 0f, -8.4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(-2.59f, 0f, -9.8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createTranslationalVector(-2.06f, 0f, -11.2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createTranslationalVector(-1.03f, 0f, -12.6f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(1f, 0f, -14f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("loops",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, -90f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .build();

    public static final AnimationDefinition WARDROBE_CLOSE = AnimationDefinition.Builder.create(1.25f)
            .addBoneAnimation("door",
                    new Transformation(Transformation.Targets.MOVE_ORIGIN,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(1f, 0f, -14f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createTranslationalVector(-1.03f, 0f, -12.6f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(-2.06f, 0f, -11.2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createTranslationalVector(-2.59f, 0f, -9.8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(-2.78f, 0f, -8.4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(-2.72f, 0f, -7f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(-2.47f, 0f, -5.6f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(-2.05f, 0f, -4.2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createTranslationalVector(-1.49f, 0f, -2.8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createTranslationalVector(-0.8f, 0f, -1.4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("door",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -90f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("loops",
                    new Transformation(Transformation.Targets.MOVE_ORIGIN,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(1f, 0f, -14f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createTranslationalVector(-1.03f, 0f, -12.6f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(-2.06f, 0f, -11.2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createTranslationalVector(-2.59f, 0f, -9.8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(-2.78f, 0f, -8.4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(-2.72f, 0f, -7f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(-2.47f, 0f, -5.6f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(-2.05f, 0f, -4.2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createTranslationalVector(-1.49f, 0f, -2.8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createTranslationalVector(-0.8f, 0f, -1.4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("loops",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -90f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .build();
}